name: Maven Build Test - Linux

on:
  push:
    branches:
      - '**'


jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
